In [159]:
# 引入所需的套件
import jieba.posseg as pseg
import pandas as pd
import string
import keras
import numpy as np
import pickle
from sklearn.model_selection \
    import train_test_split
from keras import layers

In [9]:
# 結巴切詞函數
def jieba_tokenizer(text):
    words = pseg.cut(text)
    return ' '.join([
        word for word, flag in words if flag != 'x'])

In [10]:
# 加入結巴切詞轉為list的函數
def jieba_to_list(text):
    seg_text = jieba_tokenizer(text)
    seg_list = seg_text.split(' ')
    return seg_list

In [11]:
# 檢查資料
data = pd.read_excel('/Users/wangyuda/Desktop/文字探勘/Model/all.xlsx')

In [12]:
# 去除N/A的公司資料
# N/A的原因在於這些公司在2019年間下市
data = data.dropna(inplace = False)

In [8]:
# 去除公司簡稱後面的空白
# 去除事件內容數字間的 ','，讓數字資訊更精確
for i in range(len(data)):
    data.iloc[i,1] = data.iloc[i,1].rstrip()
    data.iloc[i,7] = data.iloc[i,7].replace(',', '')

In [14]:
# 將「TCRI」 與「年」、「月」分開
TCRI = []
year = []
month = []
for i in range(len(data)):
    if type(data.iloc[i,3]) == str:
        TCRI.append(data.iloc[i,3][0])
        year.append(data.iloc[i,3][2:6])
        month.append(data.iloc[i,3][7:9])
    else:
        TCRI.append('N/A')
        year.append('N/A')
        month.append('N/A')

data.insert(3, 'TCRI-發生月', month)
data.insert(3, 'TCRI-發生年', year)
data.insert(3, 'TCRI', TCRI)


In [163]:
data

個股代號            公司簡稱       事件日 TCRI TCRI-發生年 TCRI-發生月  \
0      1218  泰山              20190101    6     2018       09   
1      1503  士電              20190101    4     2018       09   
2      1504  東元              20190101    4     2018       09   
3      1709  和益              20190101    5     2018       09   
4      1721  三晃              20190101    7     2018       09   
5      1817   凱撒衛            20190101    6     2018       09   
6      2064  晉椿              20190101    7     2018       09   
7      2207   和泰車            20190101    4     2018       09   
8      2330   台積電            20190101    1     2018       09   
9      2357  華碩              20190101    2     2018       09   
10     2377  微星              20190101    3     2018       09   
11     2442   新美齊            20190101    7     2018       09   
12     2724  富驛-KY           20190101    D     2018       09   
13     2750  桃禧              20190101                          
14     2852   第一保            20190101                          
15     2888   新光金            20190101                          
16     3004   豐達科            20190101    5     2018       09   
17     3167  大量              20190101    5     2018       09   
18     4104  佳醫              20190101    5     2018       09   
19     4138  曜亞              20190101    6     2018       09   
20     4168  醣聯              20190101    7     2018       09   
21     4402  福大              20190101    D     2018       09   
22     4535  至興              20190101    5     2018       09   
23     4726  永昕              20190101    7     2018       09   
24     4945    陞達科技          20190101    6     2018       06   
25     4987  科誠              20190101    5     2018       09   
26     6201   亞弘電            20190101    5     2018       09   
27     6221  晉泰              20190101    6     2018       09   
28     6251  定穎              20190101    6     2018       09   
29     6407  相互              20190101    8     2018       06   
...     ...             ...       ...  ...      ...      ...   
23673  3653  健策              20191231    4     2019       09   
23674  3682   亞太電            20191231    6     2019       09   
23675  4136  太和-KY           20191231    8     2019       06   
23676  4138  曜亞              20191231    6     2019       09   
23677  4150   優你康            20191231    8     2019       06   
23678  4170  鑫品              20191231    8     2019       06   
23679  4540    全球傳動          20191231    6     2019       09   
23680  4560  強信-KY           20191231    5     2019       09   
23681  4806  昇華              20191231                          
23682  4904  遠傳              20191231    2     2019       09   
23683  4908  前鼎              20191231    6     2019       09   
23684  4960   誠美材            20191231    D     2019       09   
23685  5278  尚凡              20191231    6     2019       09   
23686  5347  世界              20191231    2     2019       09   
23687  5383  金利              20191231    D     2019       09   
23688  5607   遠雄港            20191231    6     2019       09   
23689  6023   元大期            20191231                          
23690  6024   群益期            20191231                          
23691  6111   大宇資            20191231    7     2019       09   
23692  6265   方土昶            20191231    6     2019       09   
23693  6443  元晶              20191231    8     2019       09   
23694  6543    普惠醫工          20191231    6     2019       06   
23695  6611  方舟              20191231    8     2019       06   
23696  6625  必應              20191231                          
23697  6709  昱厚              20191231    8     2019       06   
23698  6715  嘉基              20191231    6     2019       09   
23699  6736   碩辣椒            20191231                          
23700  8028     昇陽半導體        20191231    6     2019       09   
23701  8033  雷虎              20191231    8     2019       09   
23702  8482  商億-KY           20191231    5     2019       09   

                  TCRI(年/月)  事件強度   大事

In [134]:
# 用Apply切詞
seg = []
seg = data.loc[:, '事件內容'].apply(jieba_to_list)

In [ ]:
# # 用迴圈切詞
# segment = []
# for i in range(len(data)):
#     seg_text = jieba_tokenizer(data.iloc[i,10])
#     seg_list = seg_text.split(' ')
#     segment.append(seg_list)

In [136]:
# 將切詞結果併入dataframe
data.insert(11, '切詞結果', seg)

In [25]:
# 建立文字向量用的字典
MAX_NUM_WORDS = 100000
tokenizer = keras \
    .preprocessing \
    .text \
    .Tokenizer(num_words = MAX_NUM_WORDS)

tokenizer.fit_on_texts(seg)
seg_to_number = tokenizer.texts_to_sequences(seg)

In [89]:
# 檢查數字轉換結果
print(len(seg_to_number))
seg_to_number[:4]

22775


list

In [90]:
# 將文字向量併入data
data.insert(12, '文字向量', seg_to_number)

In [27]:
# 檢查數字轉換結果
for seq in seg_to_number[:1]:
    print([tokenizer.index_word[idx] for idx in seq])

['發言', '人', '林俐婉', '內部', '調動', '由', '江巍峰', '接任']


In [91]:
# 確認各新聞文字字數狀況
for seq in data.iloc[:10,12]:
    print(len(seq), seq[:5], ' ...')

8 [453, 31, 36927, 80, 133]  ...
9 [80, 368, 132, 36928, 80]  ...
8 [419, 132, 36930, 80, 133]  ...
9 [80, 368, 132, 13753, 24477]  ...
8 [126, 151, 36932, 80, 133]  ...
8 [276, 132, 36934, 80, 133]  ...
12 [2472, 19248, 36936, 236, 26]  ...
18 [450, 38, 83, 4, 24480]  ...
9 [573, 38, 83, 56, 4]  ...
8 [52, 151, 24482, 80, 133]  ...


In [97]:
# 確認最大詞數
mean_seq_len = sum([len(seq) for seq in data.iloc[:,12]]) / len(data)
mean_seq_len

63.22656421514819

In [98]:
# 將各新聞文字字數固定
MAX_SEQUENCE_LENGTH = 63
seg_short = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(seg_to_number, 
                   maxlen=MAX_SEQUENCE_LENGTH)

# 處理 Y (大事件、小事件）

In [117]:
# 大事件轉換成數字
# 定義每一個分類對應到的索引數字
label_to_index = {
    'A_會計/財報分析': 0, 
    'F_市場交易': 1, 
    'I_產業前景': 2,
    'M_經營層': 3,
    'R_危機': 4
}

# 將分類標籤對應到剛定義的數字
y_big = data.iloc[:, 8].apply(lambda x: label_to_index[x])
y_big = np.asarray(y_big).astype('float32')

# 測試結果
y_big[:5]

# One Hot Encoding
y_big = keras.utils.to_categorical(y_big)

# 測試結果
y_big[:5]


array([3., 3., 3., 3., 3.], dtype=float32)

In [119]:
# 小事件轉換成數字
# 建立文字向量用的字典
MAX_NUM_WORDS_1 = 1000
tokenizer_1 = keras \
    .preprocessing \
    .text \
    .Tokenizer(num_words = MAX_NUM_WORDS_1)

small = []
for i in range(len(data)):
    data.iloc[i, 9] = data.iloc[i, 9].replace('_', '')
    small.append(data.iloc[i, 9])

tokenizer_1.fit_on_texts(small)
y_small = tokenizer_1.texts_to_sequences(small)

for i in range(len(data)):
    y_small[i] = y_small[i][0]
    
y_small = np.asarray(y_small).astype('float32')

# 測試結果
y_small[:5]

# One Hot Encoding
y_small = keras.utils.to_categorical(y_small)

# 測試結果
y_small[:5]

array([7., 7., 7., 7., 7.], dtype=float32)

In [ ]:
# # 小事件轉換成數字
# # 用土法煉鋼法
# label_to_index_1 = {
#     '1A_內部詐欺－未經授權行為': 0,
#     '1B_內部詐欺－竊盜與詐欺': 1,
#     '3B_工作場所－環境安全': 2,
#     '4A_客戶及產品－揭露義務': 3,
#     '4B_客戶及產品－不當行為': 4
#     '4C_客戶及產品－產品瑕疵':
#     '4D_客戶及產品－暴險':
#     '7A_作業流程－交易紀錄':
#     '7B_作業流程－監控與報告':
#     '7C_作業流程－客戶文件':
#     '7D_作業流程－帳戶管理':
#     'AF01_財報未出具或遲交':
#     'AF02_變更會計師事務所':
#     'AF03_會計估計變動/會計政策變更':
#     'AF04_市場傳聞造假(財報舞弊)':
#     'AF05_財務警示':
#     'AF06_資產減損':
#     'AF07_財報重編':
#     'AF09_非無保留意見':
#     'AI01_延遲公告':
#     'AI02_依主管機關要求補充公告':
#     'AI03_公告不實':
#     'AI04_自結數有重大差異':
#     'FS01_股價操縱/內部人交易/庫藏股':
#     'FS02_股價暴跌或異常':
#     '':
#     '':
#     '':
#     '':
#     '':
#     '':
#     '':
#     '':
# }

# # 將分類標籤對應到剛定義的數字
# y_small = data.iloc[:, 9].apply(lambda x: label_to_index_1[x])

# y_small = np.asarray(y_small).astype('float32')

# # 測試結果
# y_small[:5]

In [146]:
# 強度轉成array
y_strength = data.iloc[:, 7] + 3
y_strength = np.asarray(y_strength).astype('float32')
y_strength = keras.utils.to_categorical(y_strength)
print(y_strength[:5])


[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
# 將切割完成的list獨立存到一個可繼續讀取的檔案
file = open(r"/Users/wangyuda/Desktop/文字探勘/Model/list.bin","wb")
pickle.dump(data.iloc[:,11],file)
file.close()

In [83]:
# 讀取list檔
list_1 = []
file = open(r"/Users/wangyuda/Desktop/文字探勘/Model/list.bin","rb")
list_1 = pickle.load(file)

In [149]:
# 切割資料為兩部分：訓練部分與驗證部分
VALIDATION_RATIO = 0.1
# 小彩蛋
RANDOM_STATE = 9527

x = seg_short

x_train, x_val, \
yb_train, yb_val, \
ys_train, ys_val = \
    train_test_split(
        x, y_big, y_small, 
        test_size=VALIDATION_RATIO, 
        random_state=RANDOM_STATE
)

In [169]:
y_small[:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0.

In [170]:
ys_train.value_counts()

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'